services:
  postgres:
    image: postgres:17
    container_name: cms-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: strong-p@ssword
      POSTGRES_DB: cms_api
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: cms-redis
    ports:
      - "6379:6379"

  minio:
    image: minio/minio
    container_name: cms-minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: strong-p@ssword
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  postgres_data:
  minio_data: